export class Storage {
    public static REVIZE_SIZE_HOR = 'revize_hor';
    public static REVIZE_SIZE_TOP_LEFT = 'revize_tl';
    public static REVIZE_SIZE_BOTTOM_LEFT = 'revize_bl';
}

export enum DO_STATES {
    DIGITAL_OBJECT_STATE_NEW = "NEW",
    DIGITAL_OBJECT_STATE_EDITED = "EDITED",
    DIGITAL_OBJECT_STATE_ACCEPTED = "ACCEPTED",
    DIGITAL_OBJECT_STATE_REJECTED = "REJECTED",
    DIGITAL_OBJECT_STATE_UPLOADED = "UPLOADED",
    DIGITAL_OBJECT_STATE_GENERATED = "GENERATED"
} 

export enum BATCH_STATES {
    BATCH_STATE_PLANNED = "PLANNED",
    BATCH_STATE_RUNNING = "RUNNING",
    BATCH_STATE_DONE = "DONE",
    BATCH_STATE_FAILED = "FAILED"
}

export enum BATCH_SUBSTATES {
    BATCH_SUBSTATE_DOWNLOADING = "DOWNLOADING",
    BATCH_SUBSTATE_GENERATING = "GENERATING",
    BATCH_SUBSTATE_SAVING = "SAVING"
}

export enum BATCH_PRIORITIES {
    BATCH_PRIORITY_LOW = "LOW",
    BATCH_PRIORITY_MEDIUM = "MEDIUM",
    BATCH_PRIORITY_HIGH = "HIGH"
}

export enum BATCH_TYPES {
    BATCH_TYPE_MULTIPLE = "MULTIPLE",
    BATCH_TYPE_SINGLE = "SINGLE"
}